Responsive
theNishe/Bachata pull request #10
Opened 2022-06-27 17:03 UTC by theNishe

Привет, Влад! Сделала стили для всего сайта с помощью флексов. Все страшно резиновенькое. Смотри, плиз.

2022-06-27 17:09 UTC, sorokinvj commented
смотрю на разрешении 1500x и вот что вижу

Футер какой то уж очень узкий
<img width="1512" alt="Screenshot 2022-06-27 at 18 07 04" src="https://user-images.githubusercontent.com/4914235/175996986-4eeb6656-cdf9-4c4e-bb45-46730ce82d30.png">

Текст не оч хорошо видно
<img width="1345" alt="Screenshot 2022-06-27 at 18 08 23" src="https://user-images.githubusercontent.com/4914235/175997063-daafdb22-aab2-4bf3-b722-e87e3f1a6cde.png">

Давай поправим!

2022-06-27 17:19 UTC, theNishe commented
> 

![image](https://user-images.githubusercontent.com/87223543/175998678-46fc4135-76d1-44e6-b3f9-e63389df0651.png)

2022-06-27 17:21 UTC, theNishe commented
а что значит текст не очень хорошо видно? на темном фоне темный текст? мы разве не будем делать так, чтобы он вниз под картинку уходил например на узких экранах? Или я неправильно поняла?

2022-06-27 17:25 UTC, theNishe commented
не. ты прав. я намудрила. футер действительно узкий. исправила

2022-06-27 17:26 UTC, sorokinvj requested changes
Привет, спасибо!

Мне кажется, все здорово. Width и Height - свойства, которые мы не хотим в принципе задавать и делаем это только, когда других способов не осталось. Нам выгодно, чтобы геометрию блоков определял контент и расстояние от других элементов.

2022-06-27 17:26 UTC, sorokinvj commented on index.html
> +                    <p class="personal-data-agreement">Нажимая на кнопку вы даёте согласие на обработку персональных данных <!--ссылка--></p>
давай уберем комментарий с 77 строчки

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  height: 35px;
давай уберем `height` совсем

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  letter-spacing: 0em;
давай уберем это свойство

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  letter-spacing: 0em;
–

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  width: 25%;
это лишнее

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  width: 38%;
давай это уберем, и у нас все встанет на место

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  margin-right: 2%;
лучше указать здесь в пикселях

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  display: inline-block;
это лишнее

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  width: 25%;
вообще лучше всегда использовать отступы, а не `width`, особенно когда речь о тексте, здесь же нам скорее нужно задать отступ слева, а не ширину текста

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  height: 387px;
нет, давай уберем height, но сделаем вертикальные отступы между элементами формы

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  text-align: center;
повторяющееся свойство (строка 278)

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  width: 50%;
нам не нужен `width` здесь

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +  filter: invert(100%);
а зачем это?

2022-06-27 17:26 UTC, sorokinvj commented on style.css
> +.terms li:not(first-child) {
здесь грамматическая ошибка, скорее всего этот селектор не применяется сейчас (а нужен ли нам он вообще?)

2022-06-27 17:28 UTC, theNishe commented on index.html
> +                    <p class="personal-data-agreement">Нажимая на кнопку вы даёте согласие на обработку персональных данных <!--ссылка--></p>
убрала

2022-06-27 17:29 UTC, theNishe commented on style.css
> +  letter-spacing: 0em;
какое?

2022-06-27 17:38 UTC, theNishe commented on style.css
> +  letter-spacing: 0em;
line-height: 60px;
  letter-spacing: 0em; убрала
  
  font-size - тоже убрать?

2022-06-27 17:52 UTC, theNishe commented on style.css
> +  width: 25%;
letter-spacing убрала. если верно поняла, что лишнее.

2022-06-27 17:54 UTC, theNishe commented on style.css
> +  text-align: center;
убрала

2022-06-27 17:54 UTC, theNishe commented on style.css
> +  width: 50%;
убрала

2022-06-27 17:57 UTC, theNishe commented on style.css
> +  filter: invert(100%);
я не понимаю, о чем речь( height 88 не нахожу в коде

2022-06-27 18:00 UTC, theNishe commented on style.css
> +.terms li:not(first-child) {
и правда, перестал работать. удалила.

2022-06-27 18:13 UTC, theNishe commented on style.css
> +  width: 25%;
здесь, если убрать width, текстовый блок растягивается широко влево и наползает на картинку.

2022-06-27 18:14 UTC, theNishe commented on style.css
> +  display: inline-block;
margin? удалила

2022-06-27 18:16 UTC, theNishe commented on style.css
> +  margin-right: 2%;
2% заменила.

2022-06-27 18:17 UTC, theNishe commented on style.css
> +  width: 38%;
убрала, встало на место.

2022-06-27 18:19 UTC, theNishe commented on style.css
> +  height: 35px;
убрала

2022-06-27 18:37 UTC, theNishe commented on style.css
> +  height: 387px;
удалила. Но чет не придумала ничего лучше, чем задать марджинами ((

2022-06-27 18:48 UTC, sorokinvj commented
> а что значит текст не очень хорошо видно? на темном фоне темный текст? мы разве не будем делать так, чтобы он вниз под картинку уходил например на узких экранах? Или я неправильно поняла?

Я прокомментировал в коде, где нужно убрать `width` чтобы все стало как в фигме

2022-06-27 18:49 UTC, sorokinvj commented on style.css
> +  filter: invert(100%);
комментарий всегда относится к последней строчке кода, которая находится выше него, (сорри, забыл сказать!). В данном случае к свойству `filter`, вопрос что он делает? зачем он тут?

2022-06-27 18:49 UTC, sorokinvj commented on style.css
> +  height: 387px;
ну это нормально!

2022-06-27 18:50 UTC, sorokinvj commented on style.css
> +  letter-spacing: 0em;
нене, только про `letter-spacing` комментарий

2022-06-27 18:50 UTC, sorokinvj commented on style.css
> +  width: 25%;
Комментарий был про `width:25%`

2022-06-27 18:51 UTC, sorokinvj commented on style.css
> +  width: 25%;
попробуй выключить его на странице, ничего не меняется как будто

2022-06-27 18:51 UTC, sorokinvj commented on style.css
> +  letter-spacing: 0em;
`letter-spacing`

2022-06-28 10:15 UTC, theNishe commented on style.css
> +  letter-spacing: 0em;
убрала

2022-06-28 10:15 UTC, theNishe commented on style.css
> +  letter-spacing: 0em;
убрала

2022-06-28 10:17 UTC, theNishe commented on style.css
> +  width: 25%;
да, действительно. убрала.

2022-06-28 10:20 UTC, theNishe commented on style.css
> +  filter: invert(100%);
а. я сперва перепутала цвета лого и стала гуглить как инвертировать цвет. и нашла. и цвет поменялся.
в принципе, теперь можно и убрать - готово))

2022-06-28 10:23 UTC, merged