Styles for trial lesson
theNishe/Bachata pull request #6
Opened 2022-06-19 09:58 UTC by theNishe

2022-06-19 14:39 UTC, sorokinvj requested changes

2022-06-19 14:39 UTC, sorokinvj commented on style.css
> +::placeholder {
этому правилу не хватает элемента, к которому оно применяется. `::placeholder` - это псевдокласс, он может существовать только с реальным элементом: 
`div::placeholder` или `input::placeholder` или `.program::placeholder`
можно применить его ко всем элементам, для этого можно использовать *:
`*::placeholder`

2022-06-19 14:39 UTC, sorokinvj commented on style.css
> +    line-height: 135%;
давай заменим `135%` на `1.35`, так кажется понятнее, что происходит. Проценты часто используют для определения размеров блока, поэтому тут проценты могут сбить с толку

2022-06-19 14:39 UTC, sorokinvj commented on style.css
> +    letter-spacing: 0em;
это лишнее правило, оно ничего не делает

2022-06-19 14:39 UTC, sorokinvj commented on index.html
> +                <p class="program-description">Программа обучения построена таким образом, чтобы ты начал танцевать максимально быстро.</p>
почему `p` использует такой же класс, как родительский `div`? дети всегда наследуют свойства от родителей, поэтому если можно оставить только класс у `div` - тогда все дети будут использовать одинаковые свойства, а так как для `<h2 class="program-title">` есть отдельное правило, то оно "перезапишет" родительские свойства.

2022-06-19 14:39 UTC, sorokinvj commented on style.css
> +    top: -140px;
желательно не использовать отрицательные значения у элементов, я понимаю зачем ты это сделала тут. Давай запишем где-то и в будущем это исправим, добавив:

```
display: flex;
flex-direction: row;
```
к вышестоящему `<div class="trial">` - это даст команду расположить все вложенные элементы на одной строке

2022-06-19 14:39 UTC, sorokinvj commented on style.css
> +    letter-spacing: 0em;
лишнее правило

2022-06-19 14:39 UTC, sorokinvj commented on style.css
> +    background: url(/images/trial-picture.svg);
желательно вместе с `background:` всегда использовать `background-size` и `background-position` точно определяя позицию картинки. Изучи эти свойства, плиз.

2022-06-19 14:39 UTC, sorokinvj commented on style.css
>      border: 2px solid;
эту и верхнюю строчку можно объединить в одну:
`border: 2px solid #F46C20;`

2022-06-20 19:25 UTC, theNishe commented on style.css
> +::placeholder {
спасибо. 
без элемента, к которому привязан сработало. СО звездочкой. тоже. С классом попробовала - ок. 
А если нужно для двух разных элементов присвоить один стиль плейсхолдеру? Перечисление через точки двух классов не сработало. В этом случае нужно в стилях для каждого элемента свой плейсхолдер прописывать? или можно задать этим элементам один общий класс, и к нему привязать placeholder? (при условии, что не всем условным input нужно сделать один стиль)

2022-06-20 19:26 UTC, theNishe commented on style.css
> +::placeholder {
исправила на *::placeholder в данном случае

2022-06-20 19:30 UTC, theNishe commented on style.css
> +    line-height: 135%;
я это копировала из фигмы.  
и я не очень, кстати, хорошо с размерами в em и %. Пока не понимаю, как это мешает. :) 
Исправила на 1.35.

2022-06-20 19:31 UTC, theNishe commented on style.css
> +    letter-spacing: 0em;
И правда не меняет ничего. Удалила (тоже копировала из фигмы)

2022-06-20 19:33 UTC, theNishe commented on style.css
>      border: 2px solid;
сделала

2022-06-20 19:34 UTC, theNishe commented on style.css
> +    letter-spacing: 0em;
удалила. аналогично, копировала из фигмы.

2022-06-20 19:39 UTC, theNishe commented on style.css
> +    top: -140px;
ок записала себе на будущее

2022-06-20 20:56 UTC, theNishe commented on style.css
> +    background: url(/images/trial-picture.svg);
добавила, есть вопросы.

2022-06-20 20:59 UTC, theNishe commented on index.html
> +                <p class="program-description">Программа обучения построена таким образом, чтобы ты начал танцевать максимально быстро.</p>
афигеть. так можно да? 
убрала лишние классы.

2022-06-20 21:07 UTC, merged

2022-06-22 12:30 UTC, sorokinvj commented on style.css
> +::placeholder {
для двух разных элементов, просто перечисляй их через запятую:
```
input::placeholder, .some-class::placeholder {
 ...styles
}
```
@theNishe

2022-06-22 12:31 UTC, sorokinvj commented on style.css
> +    line-height: 135%;
о! лучше не копировать то, что не понимаешь, тем более Figma все время тебе хочет подсунуть абсолютные размеры и отступы для каждого элемента. Но мы это еще рассмотрим, когда будем делать responsive верстку