Footer-new-one_added
theNishe/Bachata pull request #9
Opened 2022-06-23 18:54 UTC by theNishe

Сделала футер. Разбиралась немного с флексами, вроде получше понятно, как их выстраивать.
По ним есть вопрос: если есть макет, который нужно пиксель в пиксель повторить, то я не очень понимаю, как задавать расстояния между элементами тогда (но может из-за адаптива уже нет такой жесткой привязки и как-то иначе решается)

2022-06-24 17:30 UTC, sorokinvj requested changes
Привет все в целом ок!

2022-06-24 17:30 UTC, sorokinvj commented on index.html
>              <li>Политика конфиденциальности</li>
наверное тут должны быть ссылки?

2022-06-24 17:30 UTC, sorokinvj commented on index.html
> +                <p>+79166330753</p>
`p` здесь лишнее

2022-06-24 17:30 UTC, sorokinvj commented on style.css
> +main {
```suggestion
main, header, footer {
```

2022-06-24 17:30 UTC, sorokinvj commented on style.css
> +    width: 1920px;
выше я предложил задать ширину `100%` футеру и хедеру вместе `main`. 

**Вопрос на собеседовании на позицию frontend разработчика:**
Как ты думаешь какая будет итоговая ширина у `footer`, если здесь мы оставим `width: 1920px;` и почему?

2022-06-24 17:30 UTC, sorokinvj commented on style.css
> +    display: inline-flex;
почему `inline-flex`, а не просто `flex`?

2022-06-25 08:38 UTC, theNishe commented on index.html
> +                <p>+79166330753</p>
убрала

2022-06-25 08:40 UTC, theNishe commented on style.css
> +    display: inline-flex;
не знаю. чтобы в строку отображались))

2022-06-25 08:41 UTC, theNishe commented on index.html
>              <li>Политика конфиденциальности</li>
не очень поняла коммент. где должны быть ссылки? там где "Политика конфеденциальности"? или про что это?

2022-06-25 08:43 UTC, theNishe commented on style.css
> +main {
не поняла комментарий ((

2022-06-25 08:43 UTC, theNishe commented on style.css
> +main {
а. типа добавить эти свойства для header, footer ?

2022-06-25 08:51 UTC, theNishe commented on style.css
> +main {
сделала

2022-06-26 13:00 UTC, merged